### ISSUE TITLE
7th week (8/1-8/7)

### ISSUE THREAD

**Issue by zestlee1106** [YoungPaGirls/lecture-study#7]
목표: n회
- [ ] 강의 제목 (들은 날짜)

ex)
목표: 1회
- [ ] iOS 뽀개기 (6/21)

**Comment by zestlee1106** [comment]
목표: 6회

- [x] ts: Interfaces part Two (8/1)
- [x] ts: Recap (8/4)
- [x] ts: Polymorphism (8/4)
- [x] twv: Typing Refs (8/1)
- [x] twv: Typing Computed Props (8/1)
- [x] twv: Typing Event Handlers (8/1)

**Comment by hyorin03** [comment]
목표: 1회

- [ ] 1) 순서 관리(종속성 - Dependencies)

**Comment by yeonkkk** [comment]
목표: 4회 

- [ ] OS: 디스크 스케쥴링(1)
- [ ] OS: 디스크 스케쥴링(2)
- [ ] 스프링 기본: 섹션 7
- [ ] 스프링 기본: 섹션 8
