### ISSUE TITLE
9th week (8/16-8/21)

### ISSUE THREAD

**Issue by zestlee1106** [YoungPaGirls/lecture-study#9]
목표: n회
- [ ] 강의 제목 (들은 날짜)

ex)
목표: 1회
- [ ] iOS 뽀개기 (6/21)

**Comment by zestlee1106** [comment]
목표: 8회

- [x] vt: 실 서비스에 타입스크립트를 적용하는 방법 2가지 (8/15)
- [x] vt: 점진적인 타입스크립트 적용 방식 1단계 (8/15)
- [x] vt: 점진적인 타입스크립트 적용 방식 2단계 (8/15)
- [x] vt: 점진적인 타입스크립트 적용 방식 3단계 (8/21)
- [x] vt: 두 번째 프로젝트 요약 정리 (8/21)
- [ ] vt: 뷰 플러그인과 외부 라이브러리 타입 정의
- [ ] vt: ref 속성
- [ ] vt: 뷰 이벤트 커스텀 타입 정의

**Comment by yeonkkk** [comment]
목표: 4회

- [x] 네트워크: 애플리케이션 계층 1 (8/17)
- [x] 스프링 MVC: 섹션 2 (8/17)
- [x] 스프링부트 포토그램 ch1 (8/16)
- [x] 스프링부트 포토그램 ch2 (8/17)

**Comment by hyorin03** [comment]
목표: 1회

- [ ] 2) 오퍼레이션큐의 작업 취소
